spring.application.name=consulta-clima

spring.datasource.url=jdbc:postgresql://${CLIMA_DB_HOST}/${CLIMA_DB_NAME}
spring.datasource.username=${CLIMA_DB_USER}
spring.datasource.password=${CLIMA_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true